### ISSUE TITLE
Moving all the "Shading" Pyplug to their own directory

### ISSUE THREAD

**Issue by sozap** [NatronVFX/natron-plugins#17]
I will add a new shading pyplug for doing fake reflections on a mesh
That will make 4 pyplugs all related to fake shading based on Z map / Normal Pass.
Maybe we can make a subfolder under draw to leave some space , as they are all very specific.

For the name I don't know the exact name that convey well the idea, maybe Relight or Shading ?

**Comment by olear** [comment]
We could also just add a parent category for the comunity plugins, then do whatever inside that?

**Comment by sozap** [comment]
That's an interesting question !
I don't like much the idea of having a second directory ,that will replicate the existing one.
ex : /comunity_plugins/Draw/Vignette

 For some plug I think they should integrate transparently with built-in plug. Like VectorBlur or Defocus. It's weird to have to look for them in /comunity_plug/filter/Defocus ... . And to me they are a kind of placeholder / temporary solution.
But when an official solution will be provided, then we can move them elsewhere , like a /comunity / deprecated/ folder...

Or we can do something like /filter/comunity/Defocus ? is that what you had in mind ?

What bother me the most is these reshade plug , or plug that are very specific, because they won't be used very often and by a lot of people,  for the rest , I found having transparent plugs like the Glow or Lightwrap from Coyhot is the best...

IMO this need a bit of brainstorm / debate before finding the best solution.

**Comment by sozap** [comment]
let's move all the pyplugs related to relighting to a /Draw/Relight/ directory , that will make more sense like that I think... I can take care of this in a few days.
