### ISSUE TITLE
Prepare for first release

### ISSUE THREAD

**Issue by olear** [NatronVFX/natron-plugins#20]
So, we already have several plugins, so I was thinking about doing a release on Saturday (or Sunday).

TODO:
 * Fix installer for all platforms (will only be compatible with RB-2.1 snapshots and 2.1.3+)
 * Review author credits
 * Review licenses
 * Add last-minute plugins(?)
 * Bug testing/fixing
 * Setup a repository for future upgrades (SourceForge? I also have a private server that could handle it)

I'm unable to do any work on the installer until Friday after work, but that should be enough time.

**Comment by sozap** [comment]
Great News !

- Last-minute plugins : I've the ReFlect nearly done, for the rest I'm not sure I'll have time to make them.

- Credits and Licences : I don't know much about how this work.
Some shader code or plug have no licences , some of them do, If you can brief me on were to put the info, what is need ect...

- Setup a repository for future upgrades : I've got no idea on that , do what you think is best !

- For the bugs maybe we can do a RC and let people crashtest them ? 
That may let us a window to polish a few details as well (licences/doc etc...) and not rush too much into it.

- One last thing is , between the description in the .py , in the .xml, and in the README.md , there are several differences. Do we need to have them all the same ?

**Comment by olear** [comment]
* Then ReFlect will be the last plugin before release
* I will take care of the credits and licenses. The default license (if none exists) for plugins will be GPL2+, and shader code CC-BY. As long as the license is compatible with GPL we are good.
* Then we do a RC this weekend.
* The content in the XML is just for the installer, does not need to be the same as in the PY or README. The README should just contain a short description and a screenshot. The PY should have the most information as it will integrate with the documentation system included in Natron.

**Comment by sozap** [comment]
Perfect, you rock !
I will be a bit busy until the end of the week but I'll do my best to check the .py files !

**Comment by olear** [comment]
Sorry for the delay, but I'm ready to do a release. I will start testing the installer and go from there.

**Comment by olear** [comment]
Installer test: [NCP-1.0beta1-Linux-64.zip](https://github.com/NatronVFX/natron-plugins/files/488234/NCP-1.0beta1-Linux-64.zip)

**Comment by sozap** [comment]
great news, I'll try the installer too . It was a good thing to wait a little bit anyway as there as been cool contributions these last days , so far so good !

**Comment by olear** [comment]
I will release a stable version today. I disabled SSAO in the installer until it's fixed. Any other issues I should know about? If not the plugins will be released as-is.

I will sync our releases with Natron. So our first release will be 2.1.7.
