### ISSUE TITLE
ReFlect Plugin doesn't load

### ISSUE THREAD

**Issue by PostPollux** [NatronVFX/natron-plugins#23]
When I try to add the ReFlect Plugin it always results in an error message: "Cannot create PyPlug:KnobChoice::setValueFromLabel: unknown label Impulse"

I'm using Natron 2.1.3 

Any idea?

**Comment by sozap** [comment]
Hum, Impulse is the filtering type of the STmap inside the Pyplug, I'll see how to fix this. Maybe in a few day ...

BTW , Thanks for the report and the various contribution to the repository !
