### ISSUE TITLE
AuthorityFX Plugins

### ISSUE THREAD

**Issue by aditiapratama** [NatronVFX/natron-plugins#24]
This is based on Nuke, [AuthorityFX free plugins](https://github.com/AuthorityFX/afx-nuke-plugins).

Might be useful if also available for Natron.

**Comment by olear** [comment]
How are you going to port this to PyPlugs? AuthorityFX is C++ plugins for Nuke SDK.

**Comment by aditiapratama** [comment]
ah yeah I just realized after posting this :| , I was thought to treat it as OFX plugins in Natron

**Comment by sozap** [comment]
I've looked at the code and it seems hard to translate to shadertoy or something else to me... The plugin that look very interesting to have IMO is the antialias filter, that can be a cool addition. But I don't see how to start from here ... I close the issue , but if you think there is something to do with it, feel free to re-open...
