### ISSUE TITLE
remove edge blur pyplug

### ISSUE THREAD

**Issue by PostPollux** [NatronVFX/natron-plugins#38]
I think we can remove the Edgeblur PyPlug as there is now an officially one bundled with Natron which seems to work better. Any thoughts on this?

**Comment by olear** [comment]
Sounds good to me. I will do a new release tomorrow since Natron 2.1.9 is out.

**Comment by olear** [comment]
Btw, don't remove the plugin, we just put it in a Pasture folder and disable the plugin from the installer.

**Comment by PostPollux** [comment]
Ok, sounds good to me! Are you doing it?

**Comment by olear** [comment]
Ok, I will do it.
