### ISSUE TITLE
Create a antialiasing Pyplug

### ISSUE THREAD

**Issue by sozap** [NatronVFX/natron-plugins#47]
Can be very useful to AA some passes (Z,IDMask ect...) and maybe useful for other applications as well...
Maybe this one is simple enough to be converted to Shadertoy : 

http://www.geeks3d.com/20110622/fxaa-3-version-8-source-code-released/

https://github.com/mattdesl/glsl-fxaa

MSAA seems better, but maybe harder to implement... 
If someone has ideas ... (other algorithm, techniques ect... ) I'll look into it when I'll have time, if someone else want to give it a try it will be much appreciated...

**Comment by PostPollux** [comment]
This would be indeed nice for id passes.  Well, I've never written a shadertoy shader and would have to learn it first. Maybe at some point in time I could look into it, but it wouldn't be too soon....
Good luck with your implementation attempt!

**Comment by CameraRick** [comment]
I think some crude alphas could benefit from this, too :)

There's a relatively simple way to (crudely) anti alias with a Matrix, but obviously the results are not as good. I have no skill with programming in any way, unfortunately :(

**Comment by sozap** [comment]
Finally, I couldn't stop myself to give it a go !
I was a bit disappointed by the result, MSAA or other algorithm can give better result but it's a lot harder to implement...
Anyway let try to apply this Pyplug to the year 2017 and see if we can get a slightly smoother world...

**Comment by PostPollux** [comment]
Now that was fast! Thank you I tested it with the image of their demo: http://mattdesl.github.io/glsl-fxaa/demo/
And the result in Natron looks exactly the same as in the demo. So I think it works pretty good. Although I haven't tested it with stuff like id passes.

But there seems to be a bug! The blur node inside has NO Expressions. The "Blur Filter" checkbox only enables and disables the Transform nodes, not the blur node.

**Comment by sozap** [comment]
Hey ! thanks, that's indeed a bug ! thanks for testing the plug.
I think FXAA can work pretty well in some cases, but in other it's not that great...
At least it's better than nothing for now...
you can check my tests here : https://github.com/NatronVFX/natron-plugins/blob/master/Filter/Antialiasing/README.md
