### ISSUE TITLE
Edgeblur of the Fuse plugin broken

### ISSUE THREAD

**Issue by PostPollux** [NatronVFX/natron-plugins#51]
The EdgeBlur of the "Fuse" plugin seems to be broken.
It doesn't change anything when I play with the slider. Opening the plugin shows that this node has some issues with multiple inputs again... There are two source inputs and two mask inputs.

**Comment by sozap** [comment]
Ok, there where improvements to the EdgeBlur node (which is a Pyplug) , maybe Pyplug inside Pyplugs doesn't cope well with updates.
Maybe it can be a good habit to convert them to group so they stay as they should.
I've send a message to FabioF17 so he can have a look at it.

**Comment by sozap** [comment]
FabioF made the fix

**Comment by PostPollux** [comment]
Still the same! Not fixed. I don't know if it's a problem of the plugin or of Natron itself.
![bug](https://cloud.githubusercontent.com/assets/9008901/22852623/125ef24c-f040-11e6-9975-4058b3bc825a.png)
But as you can see there are still multiple inputs. Unfortunately it even got worse, as now my output is completely black with this plugin, whereas in the last version everything worked but the edgeblur.

@fabiof17 did you try to convert that pyplug to a group?

**Comment by fabiof17** [comment]
I've converted the internal EdgeBlur to a group and updated the Repository.
Have a try.


2017-02-11 9:58 GMT+01:00 Johannes Wünsch <notifications@github.com>:

**Comment by PostPollux** [comment]
Ok, the multiple inputs are gone now, but the edge blur is still not working. The problem is that the "Merge7" node outputs the alpha of the background and not the one of the foreground. If I change that, it works fine.

**Comment by fabiof17** [comment]
Are you running Natron on Mac by any chance. Because i've noticed Merge
nodes don't behave exactly the same compares tout Windows version.

Le samedi 11 février 2017, Johannes Wünsch <notifications@github.com> a
écrit :

**Comment by PostPollux** [comment]
No, I'm running it under Linux Manjaro. I don't have a Mac to test. Does it work correctly on your side with Windows?
If that's the case I think we should file a bug report on the Natron repository

**Comment by fabiof17** [comment]
I've fixed the Merge issue. It was a mistake, not a bug at all.
And i've added a 'EdgeBlur' entry in the bottom 'Display' pulldown menu.


2017-02-12 11:54 GMT+01:00 Johannes Wünsch <notifications@github.com>:

**Comment by PostPollux** [comment]
Thanks for your continous effort! Now it works!
