### ISSUE TITLE
Volume Rays Flicker broken

### ISSUE THREAD

**Issue by PostPollux** [NatronVFX/natron-plugins#52]
@fabiof17  
I guess the flickering in Volume Rays is broken or not implemented yet. There is a speed value which implies that there is a noise that automatically creates a flicker effect, even with just a still frame as input. But this is not the case.

I looked into the plugin and I couldn't find any node, that uses that speed value in some way. Maybe I just missed it. I guess it should animate the "Z0" value of the noise nodes...

**Comment by fabiof17** [comment]
Yes indeed it was a mistake.
It's been fixed.

Thanks :)

2017-02-12 13:42 GMT+01:00 Johannes Wünsch <notifications@github.com>:

**Comment by PostPollux** [comment]
Thanks for fixing, unfortunately it still didn't work as I told you something wrong. ;) 
The expression needed to be on the "ZSlope" Value and not "Z0". I fixed it, so now everything works as expected.
