### ISSUE TITLE
ip_noisedistort big noise doesn't do anything

### ISSUE THREAD

**Issue by razvanc-r** [NatronVFX/natron-plugins#63]
I think I tracked the issue here. 

Am not 100% sure, my first time using natron so...

![image](https://user-images.githubusercontent.com/1177508/36611902-486958fa-18d5-11e8-8c16-a81a4830dc72.png)

**Comment by CameraRick** [comment]
Hi razvanc,

many of my tools (lp, not ip btw) are broken because of a bugged Shuffle behaviour. I'm re-working all of them over easter so it's hopefully fixed soon.

Sorry I didn't read this earlier! :(
