### ISSUE TITLE
Port ShaderToy Sharpen ?

### ISSUE THREAD

**Issue by sozap** [NatronVFX/natron-plugins#9]
Have a look if it's worth porting it, as there is already some sharpen filter inside Natron.
https://forum.natron.fr/t/shadertoy-natron-2-1-0/810

**Comment by olear** [comment]
I don't know, we already have a couple of sharpen plugins already in openfx-misc, I also have a OpenCL sharpen plugin in openfx-arena.

If it has any value (better and/or faster) why not(?).

**Comment by sozap** [comment]
Yes totally agree!  Someone need to investigate a bit to see if it's worth, I may do that but it's a low priority for me.
